### ISSUE TITLE
Organization Header

### ISSUE THREAD

**Issue by TheLolkPlays** [jekalmin/extended_openai_conversation#100]
Hi, i don't know how everyone uses API organizations, but theoretically I don't believe there would be any issues using different models as long as your subscription allows it. I don't know if there is a way to do this, but it would be verry nice to be able to add the OpenAI-Organization header in the API calls.
https://platform.openai.com/docs/api-reference/organization-optional
The only settings I can see are the following:
![image](https://github.com/jekalmin/extended_openai_conversation/assets/99554877/9138c673-172a-4d12-9df6-b666589755ff)

An example of usage would be to use 3.5 turbo with personal subscription but gpt-4-1106-preview with a subsctiption?

**Comment by a-d-r-i-a-n-d** [comment]
You can change the model in Conversation agent setting after the installation.
<img width="598" alt="Screenshot 2024-01-15 at 13 04 48" src="https://github.com/jekalmin/extended_openai_conversation/assets/125617841/fbcce96c-ff8b-4942-813c-c40f88b2e4c8">

**Comment by TheLolkPlays** [comment]
Hey @a-d-r-i-a-n-d, I was not referring to the model :) I was referring to the thought when you have multiple assistants and use multiple models and might want to choose which consumption subscription it uses. Some people might have personal and or organizational consumptions.

This is done rather easily:
`curl https://api.openai.com/v1/models \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "OpenAI-Organization: org-oDeZSVdysKnWSDbAiZ0ACGqK"`

https://platform.openai.com/docs/api-reference/organization-optional

However having an optional option to set this would be nice

**Comment by jekalmin** [comment]
Thanks for reporting an issue.

It would be nice to add an optional parameter, `organization`.
I will work on it soon.

**Comment by jekalmin** [comment]
`organization` is now added in [1.0.3-beta1](https://github.com/jekalmin/extended_openai_conversation/releases/tag/1.0.3-beta1).
Please try it and give a feedback.
