### ISSUE TITLE
Feature request: add entities to track used tokens

### ISSUE THREAD

**Issue by Woutch** [jekalmin/extended_openai_conversation#105]
Create some entities to track token usage. This to keep an eye on how much tokens are used to query chatgpt. 

I saw my token usage spike during the first day's and after debugging found out that this was because this was I had too many and obsolete enities exposed. This can get quite big.

Do functions count towards tokens? Or can I add as many that I want?

Thanks for this great integration!!!!
Wouter

**Comment by jekalmin** [comment]
Thanks for reporting an issue.

> Do functions count towards tokens? Or can I add as many that I want?

Yes, functions count as tokens, hence limited.

> Create some entities to track token usage

I agree that it needs a way to monitor token usage, functions called, etc...
There might be some ways to achieve this.

#### 1. Create entities which hold token usage.
- Pros
  - convenient
- Cons
  - less flexible
#### 2. Fire an event of which token usage is composed
- Pros
  - more flexible (function call or message history can also be tracked)
- Cons
  - less convenient (users have to manually set token to entity such as `input_number`)

Currently, I'm thinking of latter way(event).
Would it be enough for your case?

**Comment by Woutch** [comment]
Hi Jekalmin, 

Events would be fine for me. We can do wat we want with them. 

Many thanks for your reply!
Best regards,
Wouter

**Comment by jekalmin** [comment]
Sorry for being late.

I just released [1.0.3-beta2](https://github.com/jekalmin/extended_openai_conversation/releases/tag/1.0.3-beta2) version.
See https://github.com/jekalmin/extended_openai_conversation/pull/143 for details.

Please try it and give a feedback if possible.
Thanks.

**Comment by jekalmin** [comment]
Closing the issue.
It's released in `1.0.3` version.
