### ISSUE TITLE
Feature Request: Give more context on calendar contents

### ISSUE THREAD

**Issue by andersonimes** [jekalmin/extended_openai_conversation#114]
Hello, folks! Right now, it looks like the only information that is being passed in the prompt about calendars is whether or not there is an ongoing appointment (true/false). 

I have done a custom integration on my own where I pass all of the event details, allowing me to do things like ask for a summary of my day or if any of the other people in my family are in a meeting right now, etc. It's super useful and I could imagine other people wanting easy access to this.

**Comment by bryansampson** [comment]
I'm looking for this exact functionality as well. I have 3 calendars, work, personal, and family, that I would like to be able to output into daily agenda.

**Comment by jekalmin** [comment]
Thanks for reporting an issue!

I'm quite not sure if I understand it right.
If you add a [calendar function](https://github.com/jekalmin/extended_openai_conversation/tree/main/examples/function/calendar), you can ask about calendar.

The downside of this function I think is it requires a range of dates.
However, you might be able to ask daily schedule.

**Comment by andersonimes** [comment]
I... did not know that there was an easy way to add this. That was incredibly easy, thank you!

**Comment by jekalmin** [comment]
Closing the issue.
