### ISSUE TITLE
Error: Config flow could not be loaded

### ISSUE THREAD

**Issue by chrisc99** [jekalmin/extended_openai_conversation#115]
I have added the integration via HACS but when I try and configure the integration I get the following error:
Error Config flow could not be loaded: {"message":"Invalid handler specified"}

On restarting HA, under notifications I see the following error for extended_openai_conversation:
Invalid config
The following integrations and platforms could not be set up:

[extended_openai_conversation](https://github.com/jekalmin/extended_openai_conversation) ([Show logs](http://192.168.x.x:8123/config/logs?filter=extended_openai_conversation))
Please check your config and [logs](http://192.168.x.x:8123/config/logs).

The 2 error logs are as follows:
Log 1:
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 09:11:51 (1 occurrences)
Last logged: 09:11:51

Setup failed for custom integration 'extended_openai_conversation': Unable to import component: cannot import name 'AsyncOpenAI' from 'openai' (/usr/local/lib/python3.11/site-packages/openai/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/extended_openai_conversation/__init__.py", line 9, in <module>
    from openai import AsyncOpenAI, AsyncAzureOpenAI
ImportError: cannot import name 'AsyncOpenAI' from 'openai' (/usr/local/lib/python3.11/site-packages/openai/__init__.py)

Log2:
Logger: homeassistant.config_entries
Source: config_entries.py:2087
First occurred: 09:11:59 (3 occurrences)
Last logged: 09:29:28

Error occurred loading flow for integration extended_openai_conversation: cannot import name 'AsyncOpenAI' from 'openai' (/usr/local/lib/python3.11/site-packages/openai/__init__.py)

I have obviously done something wrong in the installation - what can I do to fix / re-install?

Thanks

**Comment by jekalmin** [comment]
Thanks for reporting an issue.

This might be related to this [issue](https://github.com/jekalmin/extended_openai_conversation/issues/75#issuecomment-1877370763).
Probably you have an integration which uses older version of openai.

If so, remove it and try again.

**Comment by chrisc99** [comment]
Thank you - deleted OpenAI Conversation, Extended OpenAI conversation and also OpenAI Response (another integration), both from HACS and Settings>Devices & services and then restarted. This seems to have worked.

**Comment by jekalmin** [comment]
Closing the issue.
