### ISSUE TITLE
Unable to find in HACS

### ISSUE THREAD

**Issue by dugdathug** [jekalmin/extended_openai_conversation#116]
I noticed in your install instructions you reference hacs, but I'm unable to locate it there.  Thought you might want to know.

**Comment by sdetweil** [comment]
i agree, not in HACS

**Comment by jekalmin** [comment]
Thanks for reporting an issue!

Sorry for misunderstanding. Currently, you should add it as a custom repository of HACS instead.
I have created a pull request to register to HACS, but it's still on progress.

**Comment by sdetweil** [comment]
they rejected it cause its not their docker container.

and they don't provide a compose file.
I don't have time to learn how to connect the parts.  

I'm traveling for the next week 

luckily the system will be with me if I get time..

**Comment by arvindagg** [comment]
I am having issue installing the integration on HA v2024.2.0. Initially the integration shows as it it has been installed but after the restart I am not able to see it neither on the file system. I am trying to install from the UI.

**Comment by Buttonskill** [comment]
@jekalmin I'm facing the same issue as @arvindagg.  Neither path allows the extended_openai_conversation to show up and allow completion (API key setup etc).

I've added as a custom repository, and I've also tried adding to '/config/custom_components/extended_openai_conversation`.

No luck.  It appears as though it's there in in HACS, but doesn't appear with other integrations post-reboot.

**Comment by Buttonskill** [comment]
Ah, I figured it out, @jekalmin and @arvindagg .  When I didn't see the manifest.json required for custom repositories, I realized there was a nested '\custom_components\extended_openai_conversation\', where I had simply dropped '\extended_openai_conversation-1.0.2\' into '\config\custom_components\'.  

Hope this helps anyone else.  It may still be worth keeping this issue open, as adding via UI was not successful.

**Comment by arvindagg** [comment]
> > I am having issue installing the integration on HA v2024.2.0. Initially the integration shows as it it has been installed but after the restart I am not able to see it neither on the file system. I am trying to install from the UI.
> 
> @arvindagg Did you figure out? It works on mine. Please attach error logs if it still exists.

Thanks for replying, I was able to fix the issue. It was something I was doing wrong.

**Comment by thiswillbeyourgithub** [comment]
Hi, I don't know if my issue is the same but I can't seem to be able to add the addon repository.

When I try to add the url to this repo I get `https://github.com/jekalmin/extended_openai_conversation is not a valid add-on repository`

Am I doing something wrong?

I can't wait to get this up and running to connect my litellm & langfuse combo with home assistant :)!

**Comment by sdetweil** [comment]
do the or part of step 1, copy the files

**Comment by thiswillbeyourgithub** [comment]
Ohhh I'm sorry. I had not yet heard about HACS and all that ecosystem so I thought it was an addon. I've now gotten it to work. Thanks a lot!

**Comment by jekalmin** [comment]
It's now available on hacs by default.
Thanks for reporting an issue.
