### ISSUE TITLE
oops.. I used the wrong apikey.. 

### ISSUE THREAD

**Issue by sdetweil** [jekalmin/extended_openai_conversation#117]
so I used an expired free apikey.. created another
edited the intergration, delete the service.. added another, used the correct apikey

made sure to export the entities again (all) 

now is the tv on say s

Oops, an error has occurred

restarted HA as well..

**Comment by jekalmin** [comment]
Thanks for reporting an issue.

Is there any error logs?
Also, did you change to correct conversation agent from assistant?

**Comment by sdetweil** [comment]
where would I find the logs? 

yes, I changed dialog manager to openai

and exposed all the entities

**Comment by sdetweil** [comment]
yes  paid apikey

exposed all, 115

then deleted all.in the expose list (don't do that!)

added lights and switches back

says don't know about that.

I deleted the last line in the integration which said don't manage local entities..

no change

**Comment by sdetweil** [comment]
i see this in the config, nothing in the ha logs
homeassistant.exposed_entities
which contains
```json
{
  "version": 1,
  "minor_version": 1,
  "key": "homeassistant.exposed_entities",
  "data": {
    "assistants": {},
    "exposed_entities": {
      "sun.sun": {
        "assistants": {
          "conversation": {
            "should_expose": true
          }
        }
      },
      "zone.home": {
        "assistants": {
          "conversation": {
            "should_expose": true
          }
        }
      }
    }
  }
}
```
![Screenshot 2024-01-27 10 15 00 AM](https://github.com/jekalmin/extended_openai_conversation/assets/1498142/1a0034f3-7af2-4a7b-acfc-1faabb618df1)

![Screenshot 2024-01-27 10 13 52 AM](https://github.com/jekalmin/extended_openai_conversation/assets/1498142/339e5a9a-df98-473b-a4f4-b8f92673a974)

**Comment by jekalmin** [comment]
Did you use `OpenAI Conversation` or `Extended OpenAI Conversation`?
From the image of "with google" above, it uses `OpenAI Conversation` as conversation agent.

Could you also capture an image of dialog and options like below?

dialog | options
--|--
<img width="300" alt="스크린샷 2024-01-29 오전 1 06 54" src="https://github.com/jekalmin/extended_openai_conversation/assets/2917984/8a862a70-4b29-470d-8bbb-f759049d380d"> | <img width="300" alt="스크린샷 2024-01-29 오전 1 10 13" src="https://github.com/jekalmin/extended_openai_conversation/assets/2917984/f29523f6-7203-4cbf-b73d-d8a3f6b1d7e1">

**Comment by sdetweil** [comment]
i git cloned the repo in the the custom components folder
sam@buildserver:~/dev/HASSio/homeassistant/config/custom_components/extended_openai_conversation$ 

i only see openai as integrations to add
![Screenshot 2024-01-28 2 34 57 PM](https://github.com/jekalmin/extended_openai_conversation/assets/1498142/d4dd63a1-bc55-4afc-940a-69124da9447c)

![Screenshot 2024-01-28 2 37 35 PM](https://github.com/jekalmin/extended_openai_conversation/assets/1498142/34af9ae6-911d-41b9-8e8e-6cfb1e1fff4e)


and only see openai as the conversation handler 

![Screenshot 2024-01-28 2 39 01 PM](https://github.com/jekalmin/extended_openai_conversation/assets/1498142/c2babd9b-cad2-4b33-877e-9d903b92f1e1)

**Comment by jekalmin** [comment]
If installed correctly, you should be able to see `Extended OpenAI Conversation` like below.

<img width="300" alt="스크린샷 2024-01-29 오전 11 43 25" src="https://github.com/jekalmin/extended_openai_conversation/assets/2917984/0cc05179-0ca2-4f60-bbb4-8897b0d5a255">

**Comment by sdetweil** [comment]
so, what did I do wrong? i put the repo folder in the custom folder and restarted ha.

**Comment by jekalmin** [comment]
You did nothing wrong.
Do you see Extended OpenAI Conversation like https://github.com/jekalmin/extended_openai_conversation/issues/117#issuecomment-1913867774 when typed "extended" in search input?

**Comment by sdetweil** [comment]
no. do not see extended

**Comment by jekalmin** [comment]
Could you capture images of folder structure?
It seems you did everything correctly, but this integration is not added.

It should look like below.
```
config
ㄴ custom_components
  ㄴ extended_openai_conversation
    ㄴ __init__.py
    ㄴ config_flow.py
    ...
```

**Comment by sdetweil** [comment]
no.. i cloned the **repo into custom_components**

the text of the readme said 
or copy the extended.... into custom components.. i didn't see a folder named that, except the repo name
i didn't drill into the structure of the repo

![Screenshot 2024-01-29 7 20 37 AM](https://github.com/jekalmin/extended_openai_conversation/assets/1498142/b4f7fe57-f8c4-4d36-b9bd-5e8f1a6062f2)

**Comment by sdetweil** [comment]
is this more correct
![Screenshot 2024-01-29 7 28 01 AM](https://github.com/jekalmin/extended_openai_conversation/assets/1498142/5fbc30f3-2e9c-4c66-9659-f6e092a8d7fe)

**Comment by sdetweil** [comment]
now it works.

so, install problem

**Comment by jekalmin** [comment]
Glad to hear that!
Sorry for lack of details in readme.
Hope you enjoy this integration :D

**Comment by sdetweil** [comment]
thanks for your attention and patience..
