### ISSUE TITLE
Error message when installing integration

### ISSUE THREAD

**Issue by rysm83** [jekalmin/extended_openai_conversation#118]
I'm trying to install the Extended OpenAi integration and I'm receiving this message Config flow could not be loaded: {"message":"Invalid handler specified"}
I tried removing from HACS and restarting Home Assistant  installed the latest non beta version, reboot again and adding the integration.  Each time I get the same error message.
I'm currently on Core 2024.1.5

**Comment by jekalmin** [comment]
Is there any error logs?

It might be caused probably by other integrations that use `openai` dependency.
Starting from `2024.x.x` core version, OpenAI dependency is changed from `0.27.2` to `1.3.8`.

Probably they use openai `0.27.2` version while `OpenAI Conversation` and `Extended OpenAI Conversation` use openai `1.3.8` version.

**Comment by rysm83** [comment]
I’m only using extended OpenAI and no other OpenAI integrations.  I noticed that this only happens if I update to above .0.9. Version. 
Currently on version .0.9 and everything seems to be working fine.

**Comment by arvindagg** [comment]
I am having issue installing the integration on HA v2024.2.0. Initially the integration shows as it it has been installed but after the restart I am not able to see it neither on the file system. I am trying to install from the UI.

**Comment by jekalmin** [comment]
Closing the issue.

@arvindagg 
Please open a new issue if it still fails.
