### ISSUE TITLE
Exceded current quota on first use?

### ISSUE THREAD

**Issue by starschild86** [jekalmin/extended_openai_conversation#120]
hi,
i am trying to setup a voice assistant based on your extension.
i am a cloud nabu casa user and i setup your integration from hass, then added an integration and got api key from my chatgpt account (free).
note: i don't use my chatgpt account since some a couple months, other than the test i have just done for this post. trying to interact with chat.openai.com does not give errors.

do i need to get a paid plan just to try? wasn't the limit set at 40.000 tokens per month on the free billing?
my usage data in chatgpt account is at zero at this link https://platform.openai.com/usage

my query:
`what time is it in toronto?
`
response:
`Sorry, I had a problem talking to OpenAI: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
`

**Comment by jaymunro** [comment]
No, it was a free $18 trial from last Jan (2023) that lasted for about 4 months, but everything needs to be paid up front for openai now. And if you ask me, it's well worth it.

**Comment by starschild86** [comment]
How much do you spend approx per month? With how many queries per day?

**Comment by jaymunro** [comment]
I just added it today and have been doing a **pile** of testing with about maybe 300-400 queries. It cost about $1.50.

**Comment by jekalmin** [comment]
Thanks @jaymunro for answer.
Closing the issue.
