### ISSUE TITLE
Local LLM Server

### ISSUE THREAD

**Issue by wont-stream** [jekalmin/extended_openai_conversation#132]
If text-generation-webui doesn't support function calling, and LocalAI is problematic for whatever reason, what is recommended to use for this plugin?

**Comment by jekalmin** [comment]
Thanks for reporting an issue.

Currently, Local LLM is not ready to use.
I also experienced a weird behavior when using LocalAI.

You might want to try [home-llm](https://github.com/acon96/home-llm) for Local LLM instead.

**Comment by wont-stream** [comment]
home-llm is perfect for my use case
