### ISSUE TITLE
FR: Ability to query image from media directory

### ISSUE THREAD

**Issue by saya6k** [jekalmin/extended_openai_conversation#140]
Currently, the `extended_openai_conversation.query_image` function can only retrieve images from publicly accessible URLs, specifically from the `www` directory, potentially leading to unnecessary public exposure of these images.

For a better fit within the Home Assistant ecosystem and as a better security practice, it would be advantageous if this function could also access media from the `media_dir`, offering a more seamless integration.

Integrations like the [Gallery Card](https://github.com/TarheelGrad1998/gallery-card) already support accessing the media directory. Alternatively, methods such as using the `/www/tmp` directory could be employed.

Adding the capability to query images from the media directory would enhance functionality and security.

**Comment by jekalmin** [comment]
I totally agree that uploading image without exposing to public is needed.
I will look into it.

**Comment by TBTHEDBA** [comment]
The new google integration can do this if needed in the mean time. google_generative_ai_conversation.generate_content

**Comment by jekalmin** [comment]
I just released [1.0.4-beta1](https://github.com/jekalmin/extended_openai_conversation/releases/tag/1.0.4-beta1).

Please try like below and give a feedback.

<img width="900" src="https://github.com/jekalmin/extended_openai_conversation/assets/2917984/fa6cf61f-35d1-43b9-908f-a8fdc6b77dec">

**Comment by AbortRetry** [comment]
Working for me thanks. Taking a snapshot of the doorbell cam and sending it out and receiving a response. Now just to work out using the response data hehe

**Comment by jekalmin** [comment]
Closing the issue.
