### ISSUE TITLE
Document usage for other languages

### ISSUE THREAD

**Issue by zolakt** [jekalmin/extended_openai_conversation#144]
Hi,

first of all, thank you @jekalmin for your work. This looks amazing.

I'm just wondering how to use this in languages other than English. I've seen you mentioned Korean in a few places, but there are no instructions on what needs to be done.

Obviously, the model needs to understand the language. But does anything else needs to be done? e.g. the prompt translated (or give an instruction to answer in another language), do the function descriptions need to be translated? etc.

I'd appreciate if you can give some instructions for this. Ideally it should be included in the readme file of the repo

**Comment by jekalmin** [comment]
Thanks for reporting an issue.

Nothing has to be done. If you ask in your language, OpenAI, with high probability, will respond in your language.
If it doesn't, try adding a prompt like `Answer in Spanish`.

I will enhance README about this.

**Comment by zolakt** [comment]
Great. Thanks for the reply.

Sorry for taking your time. I know I could have tested this out myself, but I don't have a openAI subscription currently. And for the localAI option, it takes some effort and horsepower to set up, so I was reluctant to jump directly into that route, before I asked this.
