### ISSUE TITLE
Todo Services

### ISSUE THREAD

**Issue by TBTHEDBA** [jekalmin/extended_openai_conversation#146]
![image](https://github.com/jekalmin/extended_openai_conversation/assets/40796990/c7413e3d-13bd-4a35-9c53-daef45ae1117)

Anyone else have an issue with GPT trying to use services that don't exist. I even tried implicitly telling it in its prompt to use todo.add_items

**Comment by jekalmin** [comment]
An alternative way is to register an [add_item_to_list](https://github.com/jekalmin/extended_openai_conversation/tree/main/examples/function/shopping_list#add_item_to_list).

**Comment by TBTHEDBA** [comment]
Apologies I should have given more context. 

I have that spec in place.

**Comment by TBTHEDBA** [comment]
Sorry I had a older version of that spec in place. It is working now.

**Comment by TBTHEDBA** [comment]
Working as intended

**Comment by TBTHEDBA** [comment]
Working as intended

**Comment by TGrounds** [comment]
It is working fine for me.  Thank you!
