### ISSUE TITLE
Add Italian traslation

### ISSUE THREAD

**Issue by pajeronda** [jekalmin/extended_openai_conversation#148]
`{
    "config": {
        "error": {
            "cannot_connect": "Connessione non riuscita",
            "invalid_auth": "Autenticazione non valida",
            "unknown": "Errore imprevisto"
        },
        "step": {
            "user": {
                "data": {
                    "name": "Nome",
                    "api_key": "Chiave API",
                    "base_url": "URL di base",
                    "api_version": "Versione API",
                    "skip_authentication": "Ignora autenticazione"
                }
            }
        }
    },
    "options": {
        "step": {
            "init": {
                "data": {
                    "max_tokens": "Massimo token da restituire nella risposta",
                    "model": "Modello di completamento",
                    "prompt": "Modello di prompt",
                    "temperature": "Temperatura",
                    "top_p": "Top P",
                    "max_function_calls_per_conversation": "Massime chiamate di funzione per conversazione",
                    "functions": "Funzioni",
                    "attach_username": "Allega nome utente al messaggio",
                    "use_tools": "Utilizza strumenti",
                    "context_threshold": "Soglia di contesto",
                    "context_truncate_strategy": "Strategia di troncamento del contesto quando superata la soglia"
                }
            }
        }
    },
    "services": {
        "query_image": {
            "name": "Interrogazione immagine",
            "description": "Prendere immagini e rispondere alle domande su di esse",
            "fields": {
                "config_entry": {
                    "name": "Voce di configurazione",
                    "description": "La voce di configurazione da utilizzare per questo servizio"
                },
                "model": {
                    "name": "Modello",
                    "description": "Il modello",
                    "example": "gpt-4-vision-preview"
                },
                "prompt": {
                    "name": "Prompt",
                    "description": "Il testo per chiedere riguardo all'immagine",
                    "example": "Cosa c'è in questa immagine?"
                },
                "images": {
                    "name": "Immagini",
                    "description": "Un elenco di immagini che verranno richieste",
                    "example": "{\"url\": \"https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg\"}"
                },
                "max_tokens": {
                    "name": "Max Token",
                    "description": "I token massimi",
                    "example": "300"
                }
            }
        }
    }
}
`

**Comment by jekalmin** [comment]
Thanks for your work!

If you don't mind, could you add a file in [translations](https://github.com/jekalmin/extended_openai_conversation/tree/main/custom_components/extended_openai_conversation/translations) folder and make a pull request? so that you can be registered as a [contributor](https://github.com/jekalmin/extended_openai_conversation/graphs/contributors).

See the GitHub docs for details of the steps: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by jekalmin** [comment]
Closing the issue.
