### ISSUE TITLE
Gpt3.5-turbo not creating automations

### ISSUE THREAD

**Issue by maxi1134** [jekalmin/extended_openai_conversation#151]
He claims they have been created, provides the correct YAML when asked for it, but does not create it. 

Where should I  start my debugging?

**Comment by jekalmin** [comment]
Did you add [add_automation](https://github.com/jekalmin/extended_openai_conversation/tree/main/examples/function/automation#add_automation) function?

Also, it's recommended to get notified when automation is created. (See [notice](https://github.com/jekalmin/extended_openai_conversation/tree/main/examples/function/automation#notice))

**Comment by maxi1134** [comment]
I did not! I will give it a try after work and let you know.

**Comment by jekalmin** [comment]
Closing the issue.
Please reopen it if still exists.
