### ISSUE TITLE
Catch assist pipeline events from the home assistant event bus

### ISSUE THREAD

**Issue by Risbo6** [jekalmin/extended_openai_conversation#177]
Is it possible to catch [those](https://developers.home-assistant.io/docs/voice/pipelines/#events) events from the Home Assistant event bus?

I would like to always output the [conversation response](https://developers.home-assistant.io/docs/intent_conversation_api#conversation-response) to a media_player. I'm not sure if there's an easier way to do it tho

**Comment by Risbo6** [comment]
Duplicate of https://github.com/rhasspy/wyoming-satellite/issues/96

**Comment by jekalmin** [comment]
Although it's not possible yet, the workaround might be registering a [say_tts](https://github.com/jekalmin/extended_openai_conversation/tree/v1.0.4/examples/function/say_tts#function) function, and ask it to say in your media_player.
