### ISSUE TITLE
Install with Home Assistant Docker Container (No HACS)

### ISSUE THREAD

**Issue by NG-Bullseye** [jekalmin/extended_openai_conversation#197]
Hi everyone, 

I might be missing something, but I can't seem to find a way to install this awesome Add-on with my Home Assistant Docker Container version where HACS and install from Repository is not an option. Is there a guide for this? I am quite new to Home Assistant and Docker. 

Thank you for your reply
kind regards 
Leo

**Comment by TBTHEDBA** [comment]
It's not an add-on it's an integration.

**Comment by NG-Bullseye** [comment]
Thank you got the clearing that up
