### ISSUE TITLE
Options gear icon doesn't appear

### ISSUE THREAD

**Issue by sagargp** [jekalmin/extended_openai_conversation#225]
Version: 1.0.3, installed via HACS
HA version 2024.5.5

The options button does not appear when I go to the Voice Assistant settings. See attached screenshot.

![CleanShot 2024-05-28 at 17 08 30](https://github.com/jekalmin/extended_openai_conversation/assets/194130/074b865b-5282-4519-825b-e82dcde225ab)

**Comment by rfam13** [comment]
I noticed this after one of the Home Assistant updates.  You can still get to it by going to the Extended OpenAI integration.

**Comment by sagargp** [comment]
Oh I see, thanks. Closing the issue since I can still access the settings.

**Comment by jekalmin** [comment]
Fixed in [2.0.0](https://github.com/jekalmin/extended_openai_conversation/releases/tag/2.0.0)
