### ISSUE TITLE
Possible to make it work with OpenAI compatible AI?

### ISSUE THREAD

**Issue by itispip** [jekalmin/extended_openai_conversation#237]
There are some GenAI providing 100% comptabile to OpenAI, only the baseURL difference.

Tried one of them, change the baseURL & API, submit, end with "Unexpected Error"

By the way, if based on original OpenAI Conversation by homeassitant, change above API/BaseURL will work with 3rd party.

**Comment by itispip** [comment]
Yes it can work, just skip over authentification.

**Comment by jsapede** [comment]
how did you made the setup to make it work with openai API ? i'm troying to make it work with openvino model server to get hardware acceleration on local LLM server witch is compliant with openAI API but cant setup correctly the connection / entrypoint

**Comment by itispip** [comment]
> how did you made the setup to make it work with openai API ? i'm troying to make it work with openvino model server to get hardware acceleration on local LLM server witch is compliant with openAI API but cant setup correctly the connection / entrypoint

The 3rd party AI must be 100% compatible to OpenAI API
