### ISSUE TITLE
Is this no longer maintained?

### ISSUE THREAD

**Issue by LiveForToday** [jekalmin/extended_openai_conversation#250]
I know this may not be the best place to ask and I apologize. I thank you for the work done here as well. I am just unsure if this is still maintained as I have wanted to use the memory feature where it stores the ID and has a 5 minute recall. I have waited for an updated as I see a fix has been committed. Should I use the openai that is now built into HA at this point? I have configured this extended one a lot and it works well but just hope to have some updates and if not I will move on. Thanks again.

I've added this bit to my __init__.py and restarted the integration with no luck. I am using a remote satellite so perhaps that is why?

            conversation_id = user_input.conversation_id
            messages = self.history[conversation_id]
        else:
            conversation_id = ulid.ulid()
            user_input.conversation_id = conversation_id
            conversation_id = user_input.conversation_id

**Comment by NG-Bullseye** [comment]
I am also interested in this.

**Comment by Joldiges** [comment]
> I am also interested in this.

I am incredibly disappointed in these projects being abandoned.
If just if its a dev branch that accepts pull requests.

I understand why, but still disappointed

**Comment by GSVil** [comment]
> > I am also interested in this.
> 
> I am incredibly disappointed in these projects being abandoned. If just if its a dev branch that accepts pull requests.
> 
> I understand why, but still disappointed

What do you mean by "you understand why" What's the reason?

**Comment by Joldiges** [comment]
> > > I am also interested in this.
> > 
> > 
> > I am incredibly disappointed in these projects being abandoned. If just if its a dev branch that accepts pull requests.
> > I understand why, but still disappointed
> 
> What do you mean by "you understand why" What's the reason?

People have lives and FOSS projects/contributions are rarely rewarding to the maintainers.  It's likely that this feature set will be introduced and maintained officially in the long run, making long term maintenance not overly appealing.

Ideally, the owner will be willing to redirect people to a maintained fork, but I don't see any existing.

All the same reason(s) I don't see you doing so.  I don't mean that to be mean.

**Comment by LiveForToday** [comment]
So I have put in a feature request for the HA core to add functions functionality. If it gets enough votes perhaps they will add it. Here is the link to vote. https://community.home-assistant.io/t/openai-conversation-add-functions-ability/767606

I too understand but some communication one way or the other would be polite and nice to have. I have switched to the HA core openai conversation and it has memory and I love it. It works rather well also. Does it give us the same level of customization, nope but it works well enough for me at least for now. I have one of my satellites still connected to this integration as I use the search google feature a whole lot on it. Just throwing this out there and hopefully we can get some more votes....

**Comment by GSVil** [comment]
> > > > I am also interested in this.
> > > 
> > > 
> > > I am incredibly disappointed in these projects being abandoned. If just if its a dev branch that accepts pull requests.
> > > I understand why, but still disappointed
> > 
> > 
> > What do you mean by "you understand why" What's the reason?
> 
> People have lives and FOSS projects/contributions are rarely rewarding to the maintainers. It's likely that this feature set will be introduced and maintained officially in the long run, making long term maintenance not overly appealing.
> 
> Ideally, the owner will be willing to redirect people to a maintained fork, but I don't see any existing.
> 
> All the same reason(s) I don't see you doing so. I don't mean that to be mean.
> 
> I expect the repo is at a point the OG author is happy with its functionality and use

Thanks for taking the time to respond to my question. I wish I was capable of contributing,  I just don't have the knowledge. It took me weeks to just figure out how to write a basic function for this  😊 I'm embarrassed to admit, but I asked because I'm worried this stops working and that you had some insights into something else that replaced this. I'm sort of invested in this and it would be a huge disappointment if it stops working because Home Assistant or OpenAi changed the requirements.

**Comment by LiveForToday** [comment]
So glad to get an update. thank you all for your work. I've had no issues and memory seems to be working for me now.

**Comment by jekalmin** [comment]
Apologies all.
I have recently been focusing more on my job this year.
I can't guarantee that it would never happen again.
I think it would be best to maintain it with collaborators.

**Comment by spudje** [comment]
I fear we're in a similar situation again. Not much movement here anymore :(
