### ISSUE TITLE
Media player integration - am I missing something?

### ISSUE THREAD

**Issue by JakNo** [jekalmin/extended_openai_conversation#267]
I'm quite new in all that Home Assistant stuff so please be kind to me :D
I have few enities added to my Home Assistant and few days ago I wanted to deep dive into "Assist" feature. Then I discovered this extension. I was very happy to test it and it works quite nice and fast BUT... I'm not able to use all the functions using Extended OpenAI conversation. I have for example LG TV which I can easily turn on and off using OpenAI chat but I can't for example set the volume or change the source on TV, which is possible from my Home Assistant dashboard. I also have exposed my media player entity with TV to voice assistant.
Am I missing something? Do I have to write some custom functions to use "base functions" of my enitites? Before I started I thought that "Extended OpenAI conversation" allow me to use all the base functions of my entities and if I want something more, I can write my own custom function.

**Comment by jekalmin** [comment]
There are many ways to achieve it.

1. Guide LLM to use `media_player.volume_set` for changing volumes in prompt, so it uses a base function.
2. Create your own function
3. Try with different LLM model

Keep in mind that more functions or larger prompts will consume more tokens, resulting in more costs.
The goal is to achieve what you want with minimum tokens.

**Comment by JakNo** [comment]
Oh, thank you for your hint! Much appreciate!
