### ISSUE TITLE
[Feature Request] Please add support for Grok/xAI

### ISSUE THREAD

**Issue by Starstrike** [jekalmin/extended_openai_conversation#275]
I've looked around and tried to see if using the api link for xAI would work, but unfortunately it doesn't seem to work as no entities or service shows up. I also don't see any logs indicating an issue.

The API URL for xAI/Grok is https://api.x.ai/v1

Can we get support added for this? Would like to use Grok 2 with Home Assistant to see how it compares to OpenAI.

https://docs.x.ai/docs/guides/migration

**Comment by lifuhuang** [comment]
It works for me. What's the symptom you observed? Did you get any response from Gork?

**Comment by Starstrike** [comment]
> It works for me. What's the symptom you observed? Did you get any response from Gork?

No. No entities or services are added when I enter the information and there's an error returned when you try to message Grok.

Pics attached. You can't even select a model when adding Grok as an assistant so I'm not sure why it's trying what the default openai conversation uses.

![Screenshot_20241228_095155_Home Assistant](https://github.com/user-attachments/assets/3a89c57c-d35a-40f7-b763-7bdf03138d98)
![Screenshot_20241228_095248_Home Assistant](https://github.com/user-attachments/assets/b500a8cd-16a9-4323-96f8-e68c9c3624cf)

**Comment by Starstrike** [comment]
Welp I removed the normal openai and then selected the model from the configure option and it seems to be working now.

Closing.
