### ISSUE TITLE
answering same "time"

### ISSUE THREAD

**Issue by thematrixdev** [jekalmin/extended_openai_conversation#276]
I see there is a line on the configuration

```
Current Time: {{now()}}
```

When I ask it about the current time, it always gives a same answer.
I suspect the answered time is the time when the integration is loaded?

**Comment by jekalmin** [comment]
Currently, it's the time when you start the conversation.
I might probably change fix it, so it can answer current time as HomeAssistant's native `openai_conversation` did.
