### ISSUE TITLE
Support azure openai?

### ISSUE THREAD

**Issue by AsafMah** [jekalmin/extended_openai_conversation#42]
Azure openai has the same features but a bit of a different url scheme

https://github.com/joselcaguilar/azure-openai-ha

**Comment by jekalmin** [comment]
Thanks for a suggestion.

According to [documentation](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling?tabs=python), it would not be hard to integrate Azure openai at this moment since specs seems about the same.
I will probably try this in the near future.

**Comment by jekalmin** [comment]
Could you help me implement this feature?
If I release a beta version, could you test if Azure API works?

**Comment by jekalmin** [comment]
I released in 0.0.10-beta2.
Could you try it and give a feedback?

https://github.com/jekalmin/extended_openai_conversation/pull/48#issuecomment-1868459941

**Comment by jekalmin** [comment]
Thanks for trying it!
It's released in [0.0.10](https://github.com/jekalmin/extended_openai_conversation/releases/tag/0.0.10).

Let me close the issue, and feel free to reopen the issue.

**Comment by jekalmin** [comment]
@AsafMah
If you have upgraded HA-core version to `2024.1.x`, could you try [1.0.0-beta1](https://github.com/jekalmin/extended_openai_conversation/releases/tag/1.0.0-beta1)?
There were many changes and I haven't tested Azure API yet.

**Comment by mateuszdrab** [comment]
@AsafMah could you share what base url you're using? I'm getting 404 when I use `https://{resource-name}.openai.azure.com/` as base url with API version `2023-07-01-preview`/`2023-03-15-preview`

**Comment by AsafMah** [comment]
you need to skip the validation and it should work after, so you as long as the right model is set

**Comment by mateuszdrab** [comment]
Ok I got it to work, I had to deploy a gpt-3.5-turbo-1106 model and reference it's name in the model field in the integration's configuration page.
