### ISSUE TITLE
convert the username

### ISSUE THREAD

**Issue by fantnhu** [jekalmin/extended_openai_conversation#63]
Hi! I am glad that you can attach username in the chat. Unfortunately this is not possible for us, because our name contains Hungarian (European) characters (etc.: István Pintér)
If I turn it on, I get the following error:

`Sorry, I had a problem talking to OpenAI: 'Pintér István' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.1.name'`

Is character encoding correct?

Thanks for your work! Happy New Year!

**Comment by jekalmin** [comment]
Thanks for reporting an issue!

Currently, it uses `friendly_name` of `person` entity to attach.
I might have to change it to something else such as `user_id`.

<img width="500" alt="1" src="https://github.com/jekalmin/extended_openai_conversation/assets/2917984/b7555cf8-f7c1-44d6-b897-9dde32678330">

Any suggestions are welcome.

**Comment by jekalmin** [comment]
@Teagan42
What's your thought? any ideas?

**Comment by saya6k** [comment]
How about using entity_id? since any logged user have their own person entity and we commonly use friendly_name and entity_id in exposed_entities, I think using entity_id can reduce the steps OpenAI should figure out who the speaker is.

**Comment by jekalmin** [comment]
@saya6k 

That's a good idea.
I worried that using `user_id` might make it hard to read for humans, but using `entity_id` will solve this problem!
Thanks for your suggestion!

**Comment by Teagan42** [comment]
Sorry, didn't see this thread. I think the user's id and a function to retrieve the user's detail would be a better solution than the one I had implemented.

**Comment by jekalmin** [comment]
No problem!
If we use `entity_id` (such as `person.xxxxxx`), retrieving users' detail will be possible through [get_attributes](https://github.com/jekalmin/extended_openai_conversation/tree/0.0.10/examples/function/attributes#get_attributes) function.

**Comment by jekalmin** [comment]
Sorry for being late, and it's released in `1.0.4`.
Please reopen the issue for further issues.
