### ISSUE TITLE
Add Hungarian translation (attached)

### ISSUE THREAD

**Issue by fantnhu** [jekalmin/extended_openai_conversation#64]
[hu.json](https://github.com/jekalmin/extended_openai_conversation/files/13791689/hu.json)
Hi! I have created a translation in Hungarian for the configuration interface. 

`{
    "config": {
        "error": {
            "cannot_connect": "Sikertelen kapcsolódás",
            "invalid_auth": "Érvénytelen azonosítás",
            "unknown": "Váratlan hiba"
        },
        "step": {
            "user": {
                "data": {
                    "name": "Név",
                    "api_key": "API Key (kulcs)",
                    "base_url": "Base Url"
                }
            }
        }
    },
    "options": {
        "step": {
            "init": {
                "data": {
                    "max_tokens": "A válaszban visszaküldendő maximális tokenek",
                    "model": "Teljesítési Model",
                    "prompt": "Prompt sablon",
                    "temperature": "Mérséklés",
                    "top_p": "Top P",
                    "max_function_calls_per_conversation": "Maximális funkcióhívás beszélgetésenként",
                    "functions": "Funkciók",
                    "attach_username": "Felhasználónév csatolása az üzenethez"
                }
            }
        }
    }
}`

Tested, works fine.
![image](https://github.com/jekalmin/extended_openai_conversation/assets/73642352/a75b9d24-1379-4b3f-ae38-fead87874bb0)

**Comment by jekalmin** [comment]
Thanks for your work!

If you don't mind, could you add a file in [translations](https://github.com/jekalmin/extended_openai_conversation/tree/main/custom_components/extended_openai_conversation/translations) folder and make a pull request? so that you can be registered as a [contributor](https://github.com/jekalmin/extended_openai_conversation/graphs/contributors).

**Comment by fantnhu** [comment]
> Thanks for your work!
> 
> If you don't mind, could you add a file in [translations](https://github.com/jekalmin/extended_openai_conversation/tree/main/custom_components/extended_openai_conversation/translations) folder and make a pull request? so that you can be registered as a [contributor](https://github.com/jekalmin/extended_openai_conversation/graphs/contributors).

Thanks, but that would require push access.
Feel free to use it if you want :)

**Comment by AlanGreene** [comment]
@fantnhu you don't require push access to create a PR, you can fork the repo and submit a PR from your fork. See the GitHub docs for details of the steps: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by jekalmin** [comment]
Closing the issue since `hu.json` is added.
