### ISSUE TITLE
Integration not available in HACS

### ISSUE THREAD

**Issue by AJediIAm** [jekalmin/extended_openai_conversation#66]
The instructions state that the integration can be installed via HACS, but it is not available by default. Is something broken or shall I add an instruction to att he repo manually?

**Comment by mr-biz** [comment]
This Youtube video might help you
https://youtu.be/pAKqKTkx5X4?si=1xgL4W7yayUH1ShV

**Comment by jekalmin** [comment]
@AJediIAm 
I'm sorry that I omitted to mention adding a custom repository in HACS.
However, it will be registered to default repositories in HACS soon!
I will let you know when it's available.

@mr-biz 
Thanks for sharing a video!

**Comment by AJediIAm** [comment]
@jekalmin: no need to apologies. 
I'm not much of a programmer these days, so I try to help out great projects like this by updating/improving the documentation. Some authors prefer to maintain the documentation themselves (which is fine), so this is me asking if you need any help with it.

FutureProofHomes is working on a small series focussed around this integration. It would be nice to feature the videos on this channel. I expect there will be a lot of interest in the use of Local AI together with this integration.

**Comment by jekalmin** [comment]
Thanks for your help!
I indeed need to make documentation more readable and accurate.
Please keep pointing out what needs to be done.

**Comment by shaike1** [comment]
i am facing some integration start and configuring on 2024.01 while installing the extended conversation plugin I get Please wait, starting configuration wizard for Extended OpenAI Conversation and then Error : config flow could not be loaded: unkown error. any idea?

**Comment by jekalmin** [comment]
Please try [1.0.0](https://github.com/jekalmin/extended_openai_conversation/releases/tag/1.0.0) version.
I just released it!

**Comment by shaike1** [comment]
> Please try [1.0.0](https://github.com/jekalmin/extended_openai_conversation/releases/tag/1.0.0) version. I just released it!

now it works perfectly . thnx

**Comment by jekalmin** [comment]
Closing the issue

**Comment by jekalmin** [comment]
Fixed README

https://github.com/jekalmin/extended_openai_conversation/pull/136/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L19

**Comment by jekalmin** [comment]
It's now available on hacs by default.
Thanks for reporting an issue.
