### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by squizzer73** [jekalmin/extended_openai_conversation#73]
<img width="474" alt="Screenshot 2024-01-03 at 10 47 47" src="https://github.com/jekalmin/extended_openai_conversation/assets/5830602/e6269066-63bb-4913-b46e-0ae60405b59e">
Hi, every time I try to set up the integration I put in a name and the key and get the "Unexpected Error" message, if I bypass authentication it creates it but then doesn't work (message about unable to parse the intent).

Any ideas on what idiotic mistake I am making :-)

Cheers
Mark.

**Comment by jekalmin** [comment]
Is there any logs?

**Comment by squizzer73** [comment]
Yep, sorry, they are below, looks like a duplicate of 62.

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/extended_openai_conversation/config_flow.py", line 130, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/extended_openai_conversation/config_flow.py", line 104, in validate_input
    await validate_authentication(
  File "/config/custom_components/extended_openai_conversation/helpers.py", line 154, in validate_authentication
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/lib/_old_api.py", line 39, in __call__
openai.lib._old_api.APIRemovedInV1: 

You tried to access openai.Model, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

**Comment by jekalmin** [comment]
Oh, this is the same problem with https://github.com/jekalmin/extended_openai_conversation/issues/62.
Currently, this integration doesn't support HA-core version `2024.1.x`.
Let me work on it pretty soon.

**Comment by squizzer73** [comment]
Yep, no problem, should have checked first, my bad.

**Comment by jekalmin** [comment]
No problem!
I will comment it when it's available.

**Comment by jekalmin** [comment]
Can you try [1.0.0-beta1](https://github.com/jekalmin/extended_openai_conversation/releases/tag/1.0.0-beta1)?

**Comment by squizzer73** [comment]
Just updated and that works fine now, thanks for that.
