### ISSUE TITLE
Response limited to 255 characters

### ISSUE THREAD

**Issue by Pd66** [jekalmin/extended_openai_conversation#77]
Responses are cut off to 255 characters in the Assist chat box. 

![Snímek obrazovky 2024-01-04 134546](https://github.com/jekalmin/extended_openai_conversation/assets/76690167/2b18a4e6-c003-4037-b4aa-16920174561b)

The extension parameter "maximum tokens to return in response" is set to 150. Is there a way how to get full response with 150 tokens?

**Comment by jekalmin** [comment]
Try to tweak the prompt by adding something like "Be concise".

**Comment by jekalmin** [comment]
Closing the issue.
Please reopen it for further issues.
