### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by TBTHEDBA** [jekalmin/extended_openai_conversation#81]
Can the ability to create scripts be added? I asked it to create an automation that creates and reads a unique bedtime story. The automation was correctly created but it attempted to create a script to execute as part of the process and was not able to. I asked to see the yaml for the script and it looked to be correct it just was not able to create it. 
![Screenshot_20240107-132108](https://github.com/jekalmin/extended_openai_conversation/assets/40796990/839a7317-101d-4267-89b0-abac71288bf1)

**Comment by TBTHEDBA** [comment]
Other than gpt3.generate_story not being a real service call.

**Comment by jekalmin** [comment]
Sorry for late response.
Since `gpt3.generate_story` is not a valid service, it would not work even if script is created by gpt.

**Comment by TBTHEDBA** [comment]
Thanks I realized that after I had put in the request. Just chatgpt trying to be helpful :)
