### ISSUE TITLE
When asking 'How many lights are on'  It turns on various lights.

### ISSUE THREAD

**Issue by hobbyboy** [jekalmin/extended_openai_conversation#82]
When I ask 'How many lights are on?'  It replies but will turn on certain lights.  I added "If I ask you a product count then don’t execute a function" to the configuration, it turned on less, but it still does it.

**Comment by abipster** [comment]
+1 I am having the same issue, I already tried different variations of sentences to not execute functions but it always does

**Comment by zeekens** [comment]
I had the same problem, had to update the prompt template with this monster of a sentence

"If I ask you about the current state of the home, or many devices I have, or if they are on or off, or how many devices are in a specific state, just respond with the accurate information but do not call the execute_services function."

**Comment by jekalmin** [comment]
I also experience this issue.
For me, it didn't happen when using `gpt-3.5-turbo`(in Korean Language) before, but it started to happen with `gpt-3.5-turbo-1106`.
We can try to tweak the prompt like @zeekens did.
Hope that gpt gets smarter soon.

**Comment by jekalmin** [comment]
Can you try `gpt-3.5-turbo-0125` model?

**Comment by jekalmin** [comment]
It seems fixed in `gpt-4o-mini` for me.

**Comment by jekalmin** [comment]
Closing the issue.
