### ISSUE TITLE
Something went wrong: Service cover.open not found.

### ISSUE THREAD

**Issue by darkneo29** [jekalmin/extended_openai_conversation#84]
Here is how the conversation goes.  cant seem to control garage doors. Lights and locks work fine
Assistant:How can I assist?
close garage doors
Assistant:Garage doors are closed.
open left garage door
Assistant:Something went wrong: Service cover.open not found.

**Comment by jekalmin** [comment]
Thanks for reporting an issue.

I also experienced this with other entities, but I didn't figure out how to solve it yet.
Could you try with named alias to garage doors?

I have `cover` entities (curtains and blinds) and they work fine.

**Comment by joeljody77** [comment]
I have same issue. Seems that all my covers are working fine except the garage door. all the covers that work fine are tuya based and via cloud. The garage door is an esphome device. If I ask to open I get same response as [darkneo29] . If I ask to close, it will operate the door. So if the door is open it will close it but if the door is closed it will open it. Seems to be something to do with esphome cover component.
Also I have noticed that the tuya based ones have slight different card
![image](https://github.com/jekalmin/extended_openai_conversation/assets/42470095/fc88f503-b0ed-4c8b-b6d7-fdd039daedc7)


This is the ESPhome Garage
![image](https://github.com/jekalmin/extended_openai_conversation/assets/42470095/39ea6e82-fa9a-4486-bf7d-ee137cc292e6)


Not sure if this is significant or not.

**Comment by jekalmin** [comment]
We didn't pass anything about tuya or esphome yet. The information we passed to gpt is `entity_id`, `name`, `state`, and `aliases`.

Could you change `entity_id` to be something different from `garage` and try again?
The gpt might have trained that uses `cover.open` to open garage doors while `cover.open_cover` is used for curtains and blinds.

**Comment by joeljody77** [comment]
Just tried that still no change.

![image](https://github.com/jekalmin/extended_openai_conversation/assets/42470095/64c44110-723e-4895-84be-75a56e6757f9)

changed it to be a blind. I even change the class in esphome from garage to blind.

Could it have anything to do with the garage door having a stop option not just open and close?

**Comment by joeljody77** [comment]
Found a work around
I added
If service cover.open is to be used, use cover.open_cover instead.
to the prompt. 
Works great now.

**Comment by jekalmin** [comment]
Great!
If we can guess where `cover.open` came from (eg. mqtt?), we can tell gpt not to use its grammar.
However, @joeljody77's prompt is the only way so far.

**Comment by jekalmin** [comment]
Is this problem still present when using `gpt-4o-mini`?
It seems working for me without any work around.

**Comment by jekalmin** [comment]
Closing the issue.
