### ISSUE TITLE
Not Issue, Plex-Emby search

### ISSUE THREAD

**Issue by markyskus** [jekalmin/extended_openai_conversation#91]
Hello, I love your work, working like a charm

Can you help me to transform the plex search function to emby search?

**Comment by jekalmin** [comment]
Of course.
Let's see together!

**Comment by markyskus** [comment]
cool, thanks, what do I need? I could make api key for my emby server

**Comment by jekalmin** [comment]
First of all, I want to know following.

- An example of HA service calls
- API request/response of emby search

**Comment by markyskus** [comment]
I will searching for it when Im home :)

**Comment by markyskus** [comment]
saddly there is no service call for emby now :(

**Comment by jekalmin** [comment]
Then what do you want to achieve?
Is asking gpt to search from emby enough?

**Comment by markyskus** [comment]
yes, in the first round, but nevermind, I installed plex afternoon for testing, could you please help with the voice commands for the search and for the playing? (in plex)

**Comment by jekalmin** [comment]
Good to know that plex is fine.
You can try these functions for plex.

https://github.com/jekalmin/extended_openai_conversation/tree/main/examples/function/plex

**Comment by markyskus** [comment]
sorry could you help a little bit, I have got a little time to play with this function, and I stuck a little bit
search is works fine, the play function is works fine, but how to setup the script? if I copy-paste your script, and ask for playing somethings, the answer is always that, there is no entity_id (or something like that) if I add a specifik media player to the script (apple tv) and ask for playing, something happening, the apple tv lookes like start playing (black screen with the status bar on the bottom of the screen, but after 1 second it exit

**Comment by markyskus** [comment]
sorry, other question about the searching, if I ask for search for example Avatar, the only result in the answer is the original avatar and not the avatar: way of the water, could I somehow change the searching to that way? I mean, the answer contains the avatar and th way of the water too

**Comment by markyskus** [comment]
closed
