### ISSUE TITLE
Energy Dashboard informations

### ISSUE THREAD

**Issue by enslaved2die** [jekalmin/extended_openai_conversation#94]
How can I use data from the enegry dahsboard.
e.g. how was my Consumption today compared to yesterday?

**Comment by jekalmin** [comment]
I haven't thought about this.
I might have to look up how to retrieve energy data.
Please let me know if you have any idea.

**Comment by jekalmin** [comment]
It's release since `1.0.3`.
Please refer to following.

https://github.com/jekalmin/extended_openai_conversation/tree/1.0.4/examples/function/energy
