### ISSUE TITLE
Quota Reached ERROR 429 returned

### ISSUE THREAD

**Issue by dvbit** [jekalmin/extended_openai_conversation#97]
Hi
First and foremost: thanks for developing this 

I have a free tier account and I am 100% sure (checked) that my quota is not exceeded.
Indeed in the dashboard on my account I see 0 request etc

However when prompting I get asap a 429 Quota exceeded error

**Comment by KamilKeski** [comment]
You need to add a 💳 and fund some initial credits.

**Comment by dvbit** [comment]
Thanks yes. I realised that the free tier is not including api.
